# Generated by Django 3.0.7 on 2020-07-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.TextField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
