# Generated by Django 3.0.7 on 2020-07-05 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_destination_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='booking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=30)),
                ('country', models.TextField()),
                ('Email', models.TextField()),
                ('check_in', models.DateField()),
                ('check_out', models.DateField()),
                ('Hotel', models.TextField()),
                ('Adults', models.PositiveIntegerField()),
                ('Rooms', models.PositiveIntegerField()),
                ('Childrens', models.PositiveIntegerField()),
            ],
        ),
    ]
